-- Rode esse código na aba "SQL Editor" do painel do seu Supabase para criar a tabela

CREATE TABLE quiz_results (
    id bigint generated by default as identity primary key,
    name text not null,
    score integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar políticas de segurança para permitir que o Quiz envie resultados sem a pessoa estar logada:
ALTER TABLE quiz_results ENABLE ROW LEVEL SECURITY;

-- Permitir qualquer pessoa inserir um novo resultado
CREATE POLICY "Permitir inserção anônima" ON quiz_results
FOR INSERT TO anon
WITH CHECK (true);

-- Permitir leitura da tabela para listarmos no painel admin
CREATE POLICY "Permitir leitura anônima" ON quiz_results
FOR SELECT TO anon
USING (true);

-- Permitir exclusão de resultados via painel Admin
CREATE POLICY "Permitir exclusão anônima" ON quiz_results
FOR DELETE TO anon
USING (true);
